publish:
  docker:
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/nginx-proxy
    storage_driver: overlay

    # Caching
    load: docker/image.tar
    save:
      destination: docker/image.tar
cache:
  mount:
    - docker/image.tar
